name: fit26s
channels:
- conda-forge
dependencies:
# Required dependencies
- python
- nb_conda_kernels
- ipykernel
# User requested packages
- numpy
- scipy
- pandas
- matplotlib
- seaborn
- cartopy
- geopandas
- shapely
- pyproj
- rasterio
- fiona
- rtree
- xarray
- netCDF4
- h5py
- cfgrib
- pygrib
- metpy
- siphon
- arm_pyart
- satpy
- eccodes
- pydap
- pooch
- dask
- zarr
- intake
- intake-esm
- intake-xarray
- plotly
- bokeh
- holoviews
- geoviews
- folium
- ipywidgets
- ipympl
- osmnx
- rioxarray
- earthengine-api
- hvplot
- scikit-learn
- statsmodels
- imageio
- pynio
- cartopy_offlinedata
- opencv
