name: vt26s
channels:
 - conda-forge
dependencies:
  # Required by JupyterLab
  - 'python<3.13'
  - nb_conda_kernels
  - ipykernel
  # User requested packages
  - cartopy
  - matplotlib
  - metpy
  - numpy
  - pandas
  - pip
  - siphon
  - cfgrib
  - wrf-python
  - xarray
  - ipywidgets
