name: ulv-spring-2024
channels:
 - conda-forge
dependencies:
  # Required by JupyterLab
  - python=3
  - nb_conda_kernels
  - ipykernel
  # User requested packages
  - numpy=1.19.5
  - matplotlib
  - cartopy
  - metpy
  - siphon
  - pandas<1.1.0
  - pip
  - xarray
  - ipywidgets
