name: fsu26s
channels:
  - conda-forge
dependencies:
  # Required by JupyterLab
  - python>=3.10 
  - nb_conda_kernels
  - ipykernel
  # Python executables
  - ipython
  - jupyterlab
  - jupyterlab_widgets
  # Numerical and statistical
  - numpy
  - libblas
  - numba
  - scipy
  - statsmodels
  - sympy
  - flox
  # Data visualization
  - matplotlib
  - cartopy
  - hvplot
  - geoviews
  - owslib
  - shapely
  - bokeh
  - plotly
  - seaborn
  - acgc
  # Data analysis
  - pandas
  - xarray
  - metpy
  - nc-time-axis
  # File access
  - netcdf4
  - h5netcdf
  - h5pyd
  - cftime
  - cfgrib
  - yaml
  - s3fs
  - zarr
  - openpyxl
  # Other
  - pip
  - tabulate
  - siphon
  - pooch
  - pytest
  # Optional
  - gdal
  - geopandas
  - rasterio
  - fiona
  - scikit-learn
