 name: vsu25f
 channels:
   - conda-forge
 dependencies:
  # Required by JupyterLab
  - python
  - nb_conda_kernels
  - ipykernel
  # User requested packages
  - numpy
  - matplotlib
  - cartopy
  - metpy
  - siphon
  - pandas
  - pip
  - xarray
  - ipywidgets
  - ffmpeg
  - boto3
  - botocore
  - python-awips
  - scipy
  - netcdf4
  - pip:
    - cpys
