singleuser:
  image:
    name: "unidata/uwd-fall-2024"
    tag: "xxx"

hub:
  services:
    dask-gateway:
      # This makes the gateway available at ${HUB_URL}/services/dask-gateway
      url: http://traefik-dask-gateway
      apiToken: "xxx"
