name: usage-monitoring
channels:
 - conda-forge
 - plotly
dependencies:
  - python
  - matplotlib
  - pip
  - pip:
    # It is recommended to install a package using pip as a last resort, i.e.
    # when it is not found in the conda repos
    - python-openstackclient
